// ignore_for_file: constant_identifier_names, unnecessary_const
import 'package:flutter/material.dart';
import 'models/category.dart';
import 'models/meal.dart';

const Dummy_Categories = const [
  Category(
    id: "c1",
    title: "category1",
    color: Colors.purple,
  ),
  Category(
    id: "c2",
    title: "category2",
    color: Colors.blue,
  ),
  Category(
    id: "c3",
    title: "category3",
    color: Colors.red,
  ),
  Category(
    id: "c4",
    title: "category4",
    color: Colors.purple,
  ),
  Category(
    id: "c5",
    title: "category5",
    color: Colors.blue,
  ),
  Category(
    id: "c6",
    title: "category6",
    color: Colors.red,
  ),
  Category(
    id: "c7",
    title: "category7",
    color: Colors.purple,
  ),
  Category(
    id: "c8",
    title: "category8",
    color: Colors.blue,
  ),
  Category(
    id: "c9",
    title: "category9",
    color: Colors.red,
  ),
  Category(
    id: "c10",
    title: "category10",
    color: Colors.purple,
  ),
  Category(
    id: "c1",
    title: "category11",
    color: Colors.purple,
  ),
  Category(
    id: "c2",
    title: "category12",
    color: Colors.blue,
  ),
  Category(
    id: "c3",
    title: "category13",
    color: Colors.red,
  ),
  Category(
    id: "c4",
    title: "category14",
    color: Colors.purple,
  ),
  Category(
    id: "c5",
    title: "category15",
    color: Colors.blue,
  ),
  Category(
    id: "c6",
    title: "category16",
    color: Colors.red,
  ),
  Category(
    id: "c7",
    title: "category17",
    color: Colors.purple,
  ),
  Category(
    id: "c8",
    title: "category18",
    color: Colors.blue,
  ),
  Category(
    id: "c9",
    title: "category19",
    color: Colors.red,
  ),
  Category(
    id: "c10",
    title: "category20",
    color: Colors.purple,
  ),
];

const Dummy_Meal = const [
  Meal(
    id: "m1",
    title: "a",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c1",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: true,
    isLactoseFree: false,
    isVegetarian: false,
    isVegan: false,
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
  ),
  Meal(
    id: "m2",
    title: "b",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c1",
      "c2",
      "c5",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegetarian: true,
    isVegan: true,
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
  ),
  Meal(
    id: "m3",
    title: "c",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c1",
      "c2",
      "c5",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegetarian: true,
    isVegan: true,
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
  ),
  Meal(
    id: "m4",
    title: "d",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c1",
      "c2",
      "c5",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegetarian: true,
    isVegan: true,
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
  ),
  Meal(
    id: "m5",
    title: "e",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c1",
      "c2",
      "c5",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegetarian: true,
    isVegan: true,
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
  ),
  Meal(
    id: "m6",
    title: "f",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c1",
      "c2",
      "c5",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegetarian: true,
    isVegan: true,
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
  ),
  Meal(
    id: "m7",
    title: "g",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c1",
      "c2",
      "c5",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegetarian: false,
    isVegan: false,
    duration: 20,
    complexity: Complexity.Challenging,
    affordability: Affordability.Pricey,
  ),
  Meal(
    id: "m8",
    title: "h",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c1",
      "c4",
      "c3",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegetarian: true,
    isVegan: true,
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
  ),
  Meal(
    id: "m9",
    title: "i",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c10",
      "c7 ",
      "c8",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: false,
    isVegetarian: true,
    isVegan: false,
    duration: 20,
    complexity: Complexity.Simple,
    affordability: Affordability.Affordable,
  ),
  Meal(
    id: "m10",
    title: "j",
    imageUrl:
        "https://www.archanaskitchen.com/images/archanaskitchen/10-Brands/DelMonte-KidsRecipes/Spaghetti_Pasta_Recipe_In_Creamy_Tomato_Sauce_-_Kids_Recipes_Made_With_Del_Monte-3.jpg",
    categories: [
      "c9",
      "c4",
      "c5",
    ],
    ingredients: [
      "5 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
      "1 tomato",
    ],
    steps: [
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
      "cut bengal and tomato",
    ],
    isGlutenFree: false,
    isLactoseFree: true,
    isVegetarian: false,
    isVegan: true,
    duration: 23,
    complexity: Complexity.Hard,
    affordability: Affordability.Luxurious,
  ),
];
